apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: mypassword
  POSTGRES_HOST: postgres.c74hm4pkmi2b.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: bucketproject3
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: testing
  URL: http://localhost:8100